"use client"
// Auto-generated by `npx boneyard-js build` — do not edit
import { registerBones } from 'boneyard-js'

import _sheet_grid from './sheet-grid.bones.json'

registerBones({
  "sheet-grid": _sheet_grid,
})
